export const INDEXABILITY_ISSUES_CODES = {
    // HTTP Status
    PAGE_NOT_FOUND: "PAGE_NOT_FOUND",
    SERVER_ERROR: "SERVER_ERROR",
    REDIRECT_PAGE: "REDIRECT_PAGE",
    CLIENT_ERROR: "CLIENT_ERROR",
    SOFT_404: "SOFT_404",

    // Meta Robots
    META_NOINDEX: "META_NOINDEX",
    META_NONE: "META_NONE",
    META_UNAVAILABLE_AFTER: "META_UNAVAILABLE_AFTER",
    META_NOSNIPPET: "META_NOSNIPPET",
    META_NOARCHIVE: "META_NOARCHIVE",

    // X-Robots-Tag
    X_ROBOTS_NOINDEX: "X_ROBOTS_NOINDEX",
    X_ROBOTS_NONE: "X_ROBOTS_NONE",
    X_ROBOTS_UNAVAILABLE_AFTER: "X_ROBOTS_UNAVAILABLE_AFTER",
    X_ROBOTS_NOSNIPPET: "X_ROBOTS_NOSNIPPET",
    X_ROBOTS_NOARCHIVE: "X_ROBOTS_NOARCHIVE",

    // Conflicts
    CONFLICTING_ROBOTS_DIRECTIVES: "CONFLICTING_ROBOTS_DIRECTIVES",
    META_AND_X_ROBOTS_CONFLICT: "META_AND_X_ROBOTS_CONFLICT",

    // Canonical
    MISSING_CANONICAL: "MISSING_CANONICAL",
    MULTIPLE_CANONICAL_TAGS: "MULTIPLE_CANONICAL_TAGS",
    RELATIVE_CANONICAL_URL: "RELATIVE_CANONICAL_URL",
    INVALID_CANONICAL_URL: "INVALID_CANONICAL_URL",
    NON_HTTPS_CANONICAL: "NON_HTTPS_CANONICAL",
    CANONICAL_TO_DIFFERENT_PAGE: "CANONICAL_TO_DIFFERENT_PAGE",
    CANONICAL_TO_EXTERNAL_DOMAIN: "CANONICAL_TO_EXTERNAL_DOMAIN",
    CANONICAL_ON_NON_INDEXABLE_PAGE: "CANONICAL_ON_NON_INDEXABLE_PAGE",

    // Content Type
    INVALID_CONTENT_TYPE: "INVALID_CONTENT_TYPE",
    MISSING_CONTENT_TYPE: "MISSING_CONTENT_TYPE",
    NON_HTML_CONTENT: "NON_HTML_CONTENT",
} as const;

export type IndexabilityIssueCode =
    typeof INDEXABILITY_ISSUES_CODES[keyof typeof INDEXABILITY_ISSUES_CODES];

