export const CRAWLABILITY_ISSUE_CODES = {
    // HTTP Response
    HTTP_STATUS_3XX: "HTTP_STATUS_3XX",
    HTTP_STATUS_4XX: "HTTP_STATUS_4XX",
    HTTP_STATUS_5XX: "HTTP_STATUS_5XX",

    REDIRECT_LOOP: "REDIRECT_LOOP",
    REDIRECT_CHAIN: "REDIRECT_CHAIN",
    LONG_REDIRECT_CHAIN: "LONG_REDIRECT_CHAIN",

    // robots.txt
    ROBOTS_TXT_BLOCKED: "ROBOTS_TXT_BLOCKED",
    ROBOTS_USER_AGENT_NOT_MATCHED: "ROBOTS_USER_AGENT_NOT_MATCHED",

    // Internal Links
    NO_INTERNAL_INCOMING_LINKS: "NO_INTERNAL_INCOMING_LINKS",
    NO_INTERNAL_OUTGOING_LINKS: "NO_INTERNAL_OUTGOING_LINKS",

    // Network
    SLOW_DNS_LOOKUP: "SLOW_DNS_LOOKUP",
    SLOW_TCP_CONNECTION: "SLOW_TCP_CONNECTION",
    SLOW_TLS_HANDSHAKE: "SLOW_TLS_HANDSHAKE",
    HIGH_TTFB: "HIGH_TTFB",
    HIGH_RESPONSE_TIME: "HIGH_RESPONSE_TIME",

    // Meta Robots
    META_ROBOTS_NOINDEX: "META_ROBOTS_NOINDEX",
    META_ROBOTS_NOFOLLOW: "META_ROBOTS_NOFOLLOW",

    // X-Robots-Tag
    X_ROBOTS_NOINDEX: "X_ROBOTS_NOINDEX",
    X_ROBOTS_NOFOLLOW: "X_ROBOTS_NOFOLLOW",

    // Canonical
    MISSING_CANONICAL: "MISSING_CANONICAL",
    MULTIPLE_CANONICAL: "MULTIPLE_CANONICAL",

    // Sitemap
    NOT_IN_SITEMAP: "NOT_IN_SITEMAP",
} as const;

export type CrawlabilityIssueCode =
    typeof CRAWLABILITY_ISSUE_CODES[keyof typeof CRAWLABILITY_ISSUE_CODES];

