export const RICH_RESULT_ELIGIBLE = new Set([
  "Article",
  "Book",
  "BreadcrumbList",
  "Course",
  "Dataset",
  "Event",
  "FAQPage",
  "HowTo",
  "JobPosting",
  "LocalBusiness",
  "Movie",
  "Product",
  "Recipe",
  "Review",
  "SoftwareApplication",
  "VideoObject",
]);
