import { META_DOCUMENTATION } from "@/meta/documentation.js";
import { META_ISSUE_CODES } from "@/meta/issuesCode.js";

export const META_ROBOTS_RECOMMENDATIONS = {
    [META_ISSUE_CODES.MISSING_META_ROBOTS]: {
        title: "Missing meta robots tag",
        description: "The page does not contain a meta robots tag.",
        whyItMatters:
            "Although pages are indexable by default, a meta robots tag allows you to explicitly control how search engines crawl, index, and display the page.",
        howToFix: [
            "Add a meta robots tag if explicit crawling or indexing directives are required.",
            "Use only directives that are necessary for the page.",
            "Avoid adding unnecessary restrictions."
        ],
        documentationLinks: [
            META_DOCUMENTATION.GOOGLE_ROBOTS_META_TAG
        ]
    },

    [META_ISSUE_CODES.MULTIPLE_META_ROBOTS]: {
        title: "Multiple meta robots tags detected",
        description: "The page contains more than one meta robots tag.",
        whyItMatters:
            "Conflicting robots directives can cause search engines to interpret crawling and indexing instructions unpredictably.",
        howToFix: [
            "Keep only one meta robots tag.",
            "Merge all required directives into a single tag.",
            "Remove duplicate robots tags generated by templates or JavaScript."
        ],
        documentationLinks: [
            META_DOCUMENTATION.GOOGLE_ROBOTS_META_TAG
        ]
    },

    [META_ISSUE_CODES.META_NOINDEX]: {
        title: "Page is marked as noindex",
        description: "The page contains the 'noindex' directive.",
        whyItMatters:
            "Pages marked as 'noindex' are removed from search engine indexes and cannot appear in search results.",
        howToFix: [
            "Remove the 'noindex' directive if the page should appear in search results.",
            "Keep 'noindex' only for pages that should remain hidden from search engines.",
            "Verify the directive was not added unintentionally."
        ],
        documentationLinks: [
            META_DOCUMENTATION.GOOGLE_ROBOTS_META_TAG
        ]
    },

    [META_ISSUE_CODES.META_NOFOLLOW]: {
        title: "Page is marked as nofollow",
        description: "The page contains the 'nofollow' directive.",
        whyItMatters:
            "The 'nofollow' directive instructs search engines not to follow links on the page, potentially limiting crawl discovery.",
        howToFix: [
            "Remove the 'nofollow' directive if links should be crawled.",
            "Use 'nofollow' only when intentionally preventing link discovery.",
            "Review whether the directive aligns with your SEO strategy."
        ],
        documentationLinks: [
            META_DOCUMENTATION.GOOGLE_ROBOTS_META_TAG
        ]
    },

    [META_ISSUE_CODES.META_NOARCHIVE]: {
        title: "Page is marked as noarchive",
        description: "The page contains the 'noarchive' directive.",
        whyItMatters:
            "Search engines will not show cached versions of the page when 'noarchive' is used.",
        howToFix: [
            "Remove the 'noarchive' directive unless preventing cached copies is required.",
            "Review whether cached search results are acceptable for the page."
        ],
        documentationLinks: [
            META_DOCUMENTATION.GOOGLE_ROBOTS_META_TAG
        ]
    },

    [META_ISSUE_CODES.META_NOSNIPPET]: {
        title: "Page is marked as nosnippet",
        description: "The page contains the 'nosnippet' directive.",
        whyItMatters:
            "Search engines cannot display text snippets for pages using 'nosnippet', which can reduce click-through rates.",
        howToFix: [
            "Remove the 'nosnippet' directive if search snippets should be shown.",
            "Only use 'nosnippet' when intentionally preventing snippets."
        ],
        documentationLinks: [
            META_DOCUMENTATION.GOOGLE_ROBOTS_META_TAG
        ]
    },

    [META_ISSUE_CODES.META_NOIMAGEINDEX]: {
        title: "Images are blocked from indexing",
        description: "The page contains the 'noimageindex' directive.",
        whyItMatters:
            "Images on the page will not appear in image search results.",
        howToFix: [
            "Remove the 'noimageindex' directive if images should appear in search.",
            "Use the directive only when image indexing should be prevented."
        ],
        documentationLinks: [
            META_DOCUMENTATION.GOOGLE_ROBOTS_META_TAG
        ]
    },

    [META_ISSUE_CODES.INDEX_NOINDEX_CONFLICT]: {
        title: "Conflicting index directives",
        description: "Both 'index' and 'noindex' directives are present.",
        whyItMatters:
            "Conflicting directives make it unclear whether search engines should index the page.",
        howToFix: [
            "Choose either 'index' or 'noindex'.",
            "Remove conflicting directives.",
            "Ensure only one indexing instruction is present."
        ],
        documentationLinks: [
            META_DOCUMENTATION.GOOGLE_ROBOTS_META_TAG
        ]
    },

    [META_ISSUE_CODES.FOLLOW_NOFOLLOW_CONFLICT]: {
        title: "Conflicting follow directives",
        description: "Both 'follow' and 'nofollow' directives are present.",
        whyItMatters:
            "Conflicting directives create ambiguity about whether search engines should follow links.",
        howToFix: [
            "Choose either 'follow' or 'nofollow'.",
            "Remove conflicting directives.",
            "Keep only one crawling instruction."
        ],
        documentationLinks: [
            META_DOCUMENTATION.GOOGLE_ROBOTS_META_TAG
        ]
    },

    [META_ISSUE_CODES.MAX_SNIPPET_INVALID]: {
        title: "Invalid max-snippet value",
        description: "The max-snippet directive contains an invalid value.",
        whyItMatters:
            "Invalid directive values may be ignored by search engines.",
        howToFix: [
            "Use a valid integer or -1 for max-snippet.",
            "Follow Google's supported directive values.",
            "Remove invalid values."
        ],
        documentationLinks: [
            META_DOCUMENTATION.GOOGLE_ROBOTS_META_TAG
        ]
    },

    [META_ISSUE_CODES.MAX_IMAGE_PREVIEW_INVALID]: {
        title: "Invalid max-image-preview value",
        description: "The max-image-preview directive contains an unsupported value.",
        whyItMatters:
            "Invalid values may prevent search engines from applying the intended image preview behavior.",
        howToFix: [
            "Use one of Google's supported values: none, standard, or large.",
            "Remove unsupported values."
        ],
        documentationLinks: [
            META_DOCUMENTATION.GOOGLE_ROBOTS_META_TAG
        ]
    },

    [META_ISSUE_CODES.MAX_VIDEO_PREVIEW_INVALID]: {
        title: "Invalid max-video-preview value",
        description: "The max-video-preview directive contains an invalid value.",
        whyItMatters:
            "Unsupported values may be ignored by search engines.",
        howToFix: [
            "Use a valid integer or -1.",
            "Follow Google's documented directive values.",
            "Remove unsupported values."
        ],
        documentationLinks: [
            META_DOCUMENTATION.GOOGLE_ROBOTS_META_TAG
        ]
    },

    [META_ISSUE_CODES.INDEXIFEMBEDDED_WITHOUT_NOINDEX]: {
        title: "indexifembedded used without noindex",
        description: "The 'indexifembedded' directive is present without 'noindex'.",
        whyItMatters:
            "Google only applies 'indexifembedded' when 'noindex' is also specified.",
        howToFix: [
            "Add the 'noindex' directive if 'indexifembedded' is required.",
            "Otherwise, remove 'indexifembedded'."
        ],
        documentationLinks: [
            META_DOCUMENTATION.GOOGLE_ROBOTS_META_TAG
        ]
    },

    [META_ISSUE_CODES.UNAVAILABLE_AFTER_EXPIRED]: {
        title: "Unavailable_after date has expired",
        description: "The unavailable_after directive specifies a date that has already passed.",
        whyItMatters:
            "Google may stop showing the page in search results after the specified expiration date.",
        howToFix: [
            "Update the expiration date if the content should remain searchable.",
            "Remove the directive if expiration is no longer required.",
            "Verify the configured date is correct."
        ],
        documentationLinks: [
            META_DOCUMENTATION.GOOGLE_ROBOTS_META_TAG
        ]
    }
} as const;

