

import { META_DOCUMENTATION } from "@/meta/documentation.js";
import { META_ISSUE_CODES } from "@/meta/issuesCode.js";

export const TITLE_RECOMMENDATIONS = {
    [META_ISSUE_CODES.MISSING_TITLE]: {
        title: "Missing title tag",
        description: "The page does not contain a <title> element.",
        whyItMatters:
            "The title tag is one of the most important on-page SEO signals and is commonly used as the clickable headline in search results.",
        howToFix: [
            "Add a single <title> element inside the <head> section.",
            "Write a unique and descriptive title for the page.",
            "Include the primary keyword naturally near the beginning when appropriate."
        ],
        documentationLinks: [
            META_DOCUMENTATION.GOOGLE_TITLE_LINKS
        ]
    },

    [META_ISSUE_CODES.MULTIPLE_TITLES]: {
        title: "Multiple title tags detected",
        description: "The page contains more than one <title> element.",
        whyItMatters:
            "Multiple title tags can confuse search engines about which title should be indexed and displayed in search results.",
        howToFix: [
            "Keep only one <title> element in the document.",
            "Remove duplicate title tags generated by templates or JavaScript.",
            "Verify the final rendered HTML contains exactly one title tag."
        ],
        documentationLinks: [
            META_DOCUMENTATION.GOOGLE_TITLE_LINKS
        ]
    },

    [META_ISSUE_CODES.EMPTY_TITLE]: {
        title: "Empty title tag",
        description: "The page contains a title element, but it has no content.",
        whyItMatters:
            "An empty title provides no context to search engines or users and may result in poor search result snippets.",
        howToFix: [
            "Replace the empty title with meaningful text.",
            "Describe the page accurately.",
            "Avoid generating blank titles in templates."
        ],
        documentationLinks: [
            META_DOCUMENTATION.GOOGLE_TITLE_LINKS
        ]
    },

    [META_ISSUE_CODES.DUPLICATE_TITLE]: {
        title: "Duplicate title detected",
        description: "The same page title is used on multiple pages.",
        whyItMatters:
            "Duplicate titles make it harder for search engines to distinguish between pages and reduce their relevance.",
        howToFix: [
            "Create a unique title for every indexable page.",
            "Include page-specific information such as the product, category, or location.",
            "Avoid reusing generic template titles."
        ],
        documentationLinks: [
            META_DOCUMENTATION.GOOGLE_TITLE_LINKS
        ]
    },

    [META_ISSUE_CODES.TITLE_TOO_SHORT]: {
        title: "Title is too short",
        description: "The page title is shorter than the recommended length.",
        whyItMatters:
            "Very short titles often fail to communicate enough context to users and search engines.",
        howToFix: [
            "Expand the title to better describe the page.",
            "Include important keywords naturally.",
            "Aim for approximately 30–60 characters."
        ],
        documentationLinks: [
            META_DOCUMENTATION.GOOGLE_TITLE_LINKS
        ]
    },

    [META_ISSUE_CODES.TITLE_TOO_LONG]: {
        title: "Title is too long",
        description: "The page title exceeds the recommended length.",
        whyItMatters:
            "Long titles may be truncated in search results, reducing readability and click-through rate.",
        howToFix: [
            "Remove unnecessary words.",
            "Move the most important information toward the beginning.",
            "Keep the title concise while remaining descriptive."
        ],
        documentationLinks: [
            META_DOCUMENTATION.GOOGLE_TITLE_LINKS
        ]
    },

    [META_ISSUE_CODES.TITLE_PIXEL_TOO_WIDE]: {
        title: "Title exceeds recommended pixel width",
        description: "The rendered title is wider than Google's recommended display width.",
        whyItMatters:
            "Google truncates titles based on rendered pixel width rather than character count.",
        howToFix: [
            "Shorten long words or unnecessary branding.",
            "Place important keywords near the beginning.",
            "Keep the rendered width under approximately 600 pixels."
        ],
        documentationLinks: [
            META_DOCUMENTATION.GOOGLE_TITLE_LINKS
        ]
    }
} as const;

